# docker build -t frontend-image -f Dockerfile-frontend .
# docker build -t backend-image -f Dockerfile-backend .
FROM node:alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]
