# This deploys Nginx with a NodePort service, exposing it on a specific port on each Kubernetes Node.
# kubectl apply -f nginx-nodeport.yaml

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
